export const ALL_CATEGORIE_REQUEST = 'ALL_CATEGORIE_REQUEST';
export const ALL_CATEGORIE_SUCCESS = 'ALL_CATEGORIE_SUCCESS';
export const ALL_CATEGORIE_FAIL = 'ALL_CATEGORIE_FAIL';


export const NEW_CATEGORIE_REQUEST = 'NEW_CATEGORIE_REQUEST';
export const NEW_CATEGORIE_SUCCESS = 'NEW_CATEGORIE_SUCCESS';
export const NEW_CATEGORIE_FAIL = 'NEW_CATEGORIE_FAIL';
export const NEW_CATEGORIE_RESET = 'NEW_CATEGORIE_RESET';

export const ALL_CATEGORIE_ERRORS = 'ALL_CATEGORIE_CLERA'; 
